t023_pointers:
	gcc -o t023_pointers t023_pointers.c
	./t023_pointers
	rm t023_pointers
ascii_table:
	gcc -o ascii_table ascii_table.c
	./ascii_table
	rm ascii_table
clean:
	rm t023_pointers, ascii_table